require('dotenv').config()
const express = require('express')
const cors = require('cors')
const fetch = require('node-fetch')
const app = express()
app.use(cors())
app.use(express.json())
app.use(express.static('.'))

app.get('/login', (req, res) => {
  const scope = 'user-top-read playlist-modify-public playlist-modify-private'
  const authURL = 'https://accounts.spotify.com/authorize?' + new URLSearchParams({
    response_type: 'code',
    client_id: process.env.SPOTIFY_CLIENT_ID,
    scope: scope,
    redirect_uri: process.env.REDIRECT_URI,
    show_dialog: 'true'
  })
  res.redirect(authURL)
})

app.get('/callback', async (req, res) => {
  const code = req.query.code
  const response = await fetch('https://accounts.spotify.com/api/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Authorization': 'Basic ' + Buffer.from(
        process.env.SPOTIFY_CLIENT_ID + ':' + process.env.SPOTIFY_CLIENT_SECRET
      ).toString('base64')
    },
    body: new URLSearchParams({
      grant_type: 'authorization_code',
      code: code,
      redirect_uri: process.env.REDIRECT_URI
    })
  })
  const data = await response.json()
  res.redirect('/?access_token=' + data.access_token)
})

app.post('/analyse', async (req, res) => {
  const { artists, mood, purpose, energy, decade, favouriteArtist } = req.body

  let contextBlock = ''
  if (mood) {
    contextBlock = `
Their current mood: ${mood}.
This playlist is for: ${purpose}.
Energy level: ${energy}.
Decade feel they want: ${decade}.
Artist they want more of: ${favouriteArtist}.
Use ALL of this context to make the roast even more personal and specific.`
  }

  const prompt = `You are a savage music critic. Roast this person based on their top artists: ${artists}.${contextBlock} Write like this example: "You cry to berlioz alone at 2am then pretend you're cool at the club with Bad Bunny. Drake is your roman empire and you know it." Match that exact energy and length. One short paragraph, max 3 sentences, no labels.`

  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + process.env.GROQ_API_KEY
    },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }]
    })
  })
  const data = await response.json()
  if (data.choices && data.choices[0]) {
    res.json({ result: data.choices[0].message.content })
  } else {
    res.json({ result: 'Error: ' + JSON.stringify(data) })
  }
})

app.post('/create-playlist', async (req, res) => {
  try {
    const { token, mood, purpose } = req.body

    const userRes = await fetch('https://api.spotify.com/v1/me', {
      headers: { 'Authorization': 'Bearer ' + token }
    })
    const user = await userRes.json()

    const topTracksRes = await fetch('https://api.spotify.com/v1/me/top/tracks?limit=30&time_range=medium_term', {
      headers: { 'Authorization': 'Bearer ' + token }
    })
    const topTracksData = await topTracksRes.json()

    if (!topTracksData.items || topTracksData.items.length === 0) {
      return res.status(500).json({ error: 'No top tracks found' })
    }

    const trackUris = topTracksData.items.map(t => t.uri)

    const playlistName = mood && purpose
      ? `Wavelength — ${mood} ${purpose} Mix`
      : 'Wavelength — Your Vibe'

    const playlistRes = await fetch(`https://api.spotify.com/v1/users/${user.id}/playlists`, {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + token,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: playlistName,
        description: 'Generated by Wavelength — wavelength-nx3r.onrender.com',
        public: false
      })
    })
    const playlist = await playlistRes.json()

    await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + token,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ uris: trackUris })
    })

    res.json({ playlistUrl: playlist.external_urls.spotify })

  } catch (err) {
    console.error('PLAYLIST ERROR:', err)
    res.status(500).json({ error: err.message })
  }
})

app.listen(3000, () => {
  console.log('Wavelength server running on http://localhost:3000')
})